INSERT INTO MODEL (ID, VAL) VALUES (1, 'Pavan');
INSERT INTO MODEL (ID, VAL) VALUES (2, 'Daljeet');
INSERT INTO MODEL (ID, VAL) VALUES (3, 'Santosh');
INSERT INTO MODEL (ID, VAL) VALUES (4, 'Karunakar');
INSERT INTO MODEL (ID, VAL) VALUES (5, 'TEST');
