CREATE TABLE MODEL
(
	ID NUMBER(19) NOT NULL,
	VAL VARCHAR2(50) NOT NULL,
);

CREATE TABLE company
(
	`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR2(50) NOT NULL,
	address VARCHAR2(100) NOT NULL,
	city VARCHAR2(100) NOT NULL,
	tin NUMBER(19) NOT NULL,
	phonenumber NUMBER(19) NOT NULL,
);
